[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/customs
admin_passwd = Chucam2022
db_host = 168.231.73.120
db_port = 5432
db_user = xecohil
db_password = Chucam2022++
limit_time_cpu = 1200
limit_time_real = 1800
